apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis-configmap
  namespace: dev
data:
  botPolicies.yaml: |
    bots:
    - import: (data)/meta/default-config.yaml
    - name: runner
      action: ALLOW
      remote_addresses: ["2a04:3540:1000:310:e4aa:70ff:feb6:3b0b/128","212.147.239.25/32"]
