apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./externalsecret.yaml
  - ./hr.yaml
  - ./manual-redirect-ingress.yaml
  - ../../../../templates/volsync-r2
