apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: forego-helm
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://codeberg.org/forgejo-contrib/forgejo
